name: Debugging with SSH
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

       
    # You might want to Checkout your repo first, but not mandatory
      - name: Check Out
        uses: actions/checkout@v3
    # Cleanup The Actions Workspace Using Custom Composite Run Actions
      - name: Cleanup
        uses: rokibhasansagar/slimhub_actions@main
          
      - name: Prepare the environment
        run: |
          sudo apt update
          sudo add-apt-repository universe
          sudo apt-get install fakeroot dpkg-dev libcurl4-openssl-dev python3 repo python3-pip python2 pigz -y
          sudo apt-get install aptitude -y
          sudo aptitude install bc bison build-essential ccache curl flex g++-multilib gcc-multilib git gnupg gperf imagemagick lib32ncurses5-dev lib32readline-dev lib32z1-dev liblz4-tool libncurses5 libncurses5-dev libsdl1.2-dev libssl-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev -y
          sudo aptitude install openjdk-8-jdk -y
          curl https://bootstrap.pypa.io/pip/2.7/get-pip.py --output get-pip.py
          sudo python2 get-pip.py
          rm -f get-pip.py
          sudo pip2 install pycryptodome
          sudo pip3 install pycryptodome
          
      - name: Start SSH via Ngrok
      # if: ${{ failure() }}
        run: |
          curl -sL https://gist.githubusercontent.com/retyui/7115bb6acf151351a143ec8f96a7c561/raw/7099b9db76729dc5761da72aa8525f632d8875c9/debug-github-actions.sh | bash
        env:
          # After sign up on the https://ngrok.com/
          # You can find this token here: https://dashboard.ngrok.com/get-started/setup
          NGROK_TOKEN: ${{ secrets.NGROK_TOKEN }}
          # This password you will use when authorizing via SSH
          USER_PASS: ${{ secrets.USER_PASS }}
# sb
        
      - name: sleep for 20 mins
        if: ${{ failure() }}
        run: sleep 2h
